### ISSUE TITLE
Create Reservation Workflow

### ISSUE THREAD

**Issue by TheRealKiraAI** [KiraCorbett/cs361-bbs#1]
* A system which displays inventory of available bikes and allows payment for bike orders to be processed.

**Comment by kerojosh96** [comment]
create a use case

**Comment by IrishFagan** [comment]
https://github.com/KiraCorbett/cs361-bbs/blob/01_reserve/bicycle_reservation_workflow.rb
https://github.com/KiraCorbett/cs361-bbs/blob/01_reserve/customer_reservers_bike.rb

**Comment by IrishFagan** [comment]
https://github.com/KiraCorbett/cs361-bbs/commit/5d1fd502238e28f4bd1cb649f75b6fb2c665f9c9

**Comment by WanderinCrow** [comment]
https://github.com/KiraCorbett/cs361-bbs/commit/199abab9c984477593f197cac7e68f8e5e2d51c2

**Comment by kerojosh96** [comment]
cabf77657de50e20546ed6b3208ee8be5dee7236

**Comment by WanderinCrow** [comment]
https://github.com/KiraCorbett/cs361-bbs/commit/d14a46b600e7691d5a8881a3b5b2ce084659e9dc
https://github.com/KiraCorbett/cs361-bbs/commit/d99aca68a7daa7ec74e54054351523facd92421f
https://github.com/KiraCorbett/cs361-bbs/commit/ba7ab55f25e80b85873b77b51ec7345167eced30
https://github.com/KiraCorbett/cs361-bbs/commit/3c473d1e2a0b5ad8ee65cf93a0c000c5582bda92
