### ISSUE TITLE
Create Return On Time Workflow

### ISSUE THREAD

**Issue by IrishFagan** [KiraCorbett/cs361-bbs#2]
Kiosk tracks reservation number, bike ID and payment information for bike being returned.

**Comment by GarrettGunnell** [comment]
https://github.com/KiraCorbett/cs361-bbs/commit/f76535a45b9611bd0cb90c71e461e1689666557c

**Comment by GarrettGunnell** [comment]
https://github.com/KiraCorbett/cs361-bbs/commit/53686ed520cf1ed4562acdb4d8228b8f079d1d4c
