### ISSUE TITLE
Customer Views Reservations with Kayaks

### ISSUE THREAD

**Issue by TheRealKiraAI** [KiraCorbett/cs361-bbs#7]
1. Refactoring classes to remove duplicate code.
2. Adding kayak rentals.

**Comment by WanderinCrow** [comment]
https://github.com/KiraCorbett/cs361-bbs/commit/0d74c9f8656a8796d276602d0bac7501a4fb98ea
https://github.com/KiraCorbett/cs361-bbs/commit/70993958f0877419281f6cad54c6ab089b6f2aa7
https://github.com/KiraCorbett/cs361-bbs/commit/e010d9c4b7b80d5c96a9afbe1839cc8f6357d842
https://github.com/KiraCorbett/cs361-bbs/commit/c92cf40b2018558dbfc7010cc82eb3105c19aad4
https://github.com/KiraCorbett/cs361-bbs/commit/e3cb30bfb9404bb1dfd10ac9f0299205a7857408
https://github.com/KiraCorbett/cs361-bbs/commit/cfc94ca95c04820a9780546a92e75421b72ca784
https://github.com/KiraCorbett/cs361-bbs/commit/d50a396b5fadcb45423344b2ef2569e05c429477
https://github.com/KiraCorbett/cs361-bbs/commit/e4e5dacae466ea03c91faa6dc227122cd58f9559
https://github.com/KiraCorbett/cs361-bbs/commit/b040e82963967cfa347dcf7092b3e7543e5837c9
https://github.com/KiraCorbett/cs361-bbs/commit/40b3c90055982b64ab0e76e8cd26a6ea2f5caddf
https://github.com/KiraCorbett/cs361-bbs/commit/d56010bc20fe4520082916b09a636d66d8f1bb12
https://github.com/KiraCorbett/cs361-bbs/commit/a60a7567a4a7feb8f3674fc11f970ea1d8be8515
